H = groups.matrix.Heisenberg()
print(H)
print(H.gens())
X, Y, Z = H.gens()
print(Z * X * Y**-1)
print(X * Y * X**-1 * Y**-1 == Z)
H = groups.matrix.Heisenberg(R=5)
print(H)
H = groups.matrix.Heisenberg(n=3, R=13)
print(H)